# Como ler uma planilha de excel?

In [1]:
import pandas as pd

In [10]:
dados_cotacao_petrobras = pd.read_excel(r'C:\Users\lsiqu\videos_youtube\dados_yt\dados_petro.xlsx',
                                       skiprows = 3,
                                       na_values = "nd",
                                       index_col = "data")

dados_volume_petrobras = pd.read_excel(r'C:\Users\lsiqu\videos_youtube\dados_yt\dados_petro.xlsx',
                                       skiprows = 3,
                                       na_values = "nd",
                                       index_col = "data",
                                      sheet_name = "cotacoes")

dados_volume_petrobras.dropna()

            fechamento_ajustado  abertura_ajust  min_ajust  maxima_ajust
data
2022-09-12            31.580000       32.150000  31.460000     32.730000
2022-09-09            31.790000       32.490000  31.700000     32.670000
2022-09-08            31.800000       32.310000  31.400000     32.780000
2022-09-06            32.100000       32.270000  31.510000     32.590000
2022-09-05            33.330000       33.850000  33.150000     34.110000
...                         ...             ...        ...           ...
2022-05-20            25.450721       25.275350  25.026908     25.450721
2022-05-19            24.968451       24.493488  24.354652     25.056137
2022-05-18            24.551945       24.975758  24.427724     25.253429
2022-05-17            24.961144       25.574943  24.946530     25.677242
2022-05-16            25.289965       25.026908  24.851537     25.487257

[84 rows x 4 columns]